### PR TITLE
Added option to exclude sbt resource target from Idea classpath

### PR DESCRIPTION
**Pull request by aerskine**
Usage of the new exclude.sbt.resources option can help avoid issues with resource items appearing in the classpath multiple times.

### CODE REVIEW

**Comment by mpeltonen** [comment]
Just to understand this a bit more, do the resource directories currently always appear multiple times in classpath, or just in some configurations? If latter, what is the cause?

**Comment by ijuma** [comment]
Resource directories should only appear once in the classpath as they're only added to the project where they appear as an exported dependency. I think what is being said (please correct if wrong) is that people may have the same resource item in many projects. My question would be, how do you deal with that when running things from SBT itself?

**Comment by mpeltonen** [comment]
Ah, resource _items_, not directories. Yes, that's probably the intent then. But wouldn't this option cause the resources be missing from Idea classpath altogether? Or am I still missing something?

**Comment by ijuma** [comment]
Unless the resource exists in a jar dependency instead of a project dependency. Still, seems a bit odd so better to wait for an explanation from the reporter.

**Comment by aerskine** [comment]
Hi -- when you 'Make Project' in Idea the behavior is to copy items from src/main/resources to the build output path, and src/test/resources to the test output path.

The 'Resource patterns' setting in Idea dictates what gets copied - this defaults to:

?_.properties;?_.xml;?_.gif;?_.png;?_.jpeg;?_.jpg;?_.html;?_.dtd;?_.tld;?_.ftl;?_.properties;?_.xml;?_.html;?_.dtd;?_.tld;?_.gif;?_.png;?_.jpeg;?*.jpg

Which in our case was every resource item.  Now since target/scala_2.8.0/resources was also added by the sbt-idea plugin, each item was appearing twice in the classpath.

When I investigated this I looked into overriding the Resource Pattern setting to exclude all files (that way I could keep the default plugin behavior) but I didn't see a way to do this.

Excluding the sbt resource path from being added therefore seemed the logical way forward.

I defaulted 'exclude.sbt.resources' to 'false' (ie keep current behavior)... but perhaps the name is confusing?

**Comment by ijuma** [comment]
OK, so this is another case of different behaviour required by people who build via IDEA and the ones who build via SBT. There's probably no harm in adding the requested property. In the future, it sounds like it would be nice to have a property that optimises the configuration files for the former case and another for the latter case.

**Comment by mpeltonen** [comment]
Yes, it seems like property something like 'compile.with.idea' would be in order (defaulting to false :). 

I have also used mainly sbt for compiling (alt+tab being the compile and/or run tests 'shortcut key') because it is faster and haven't hence run into this kinds of issues.

**Comment by aerskine** [comment]
'compile.with.idea' is clearer.

I've changed it, and made a small change to the implementation, and added to the README.md :=)

**Comment by mpeltonen** [comment]
Closing this, overridden by pull request 27.

**Pull request closed without merging**
