### PR TITLE
Fix compiler library in SBT 0.13.x with Scala != 2.10.2

### LINKED ISSUE #248: 1.6.0-SNAPSHOT fails to add dependency to Scala jars
Plugin fails to add dependency to Scala compiler and library jars when used with project where `scalaVersion` is `2.10.3-RC1`. As result project is not compilable.

Version of SBT used is `0.13.0-RC5`

### PR DESCRIPTION
**Pull request by retronym**
Before 0.13.0, we _always_ used to get JARs from the boot directory; now we
only seem to get these if we use the same Scala version as SBT itself (2.10.2).

This commit relaxes the filtering to handle both naming conventions.

Fixes #248

### CODE REVIEW

**Comment by mpeltonen** [comment]
Merged (and published new snapshot), thanks!

**Comment by retronym** [comment]
@mpeltonen Do you have a planned timeframe for the next stable release? We'd like to update Activator to default to Scala 2.10.3, but we can't do this until the next sbt-idea release.

Going forward, we'll test sbt-idea with new Scala builds before release; in the 2.11.x series our modularization might trigger one or two more changes.

**Comment by channingwalton** [comment]
I just tried the snapshot and I'm getting the same issue. What can I do to help fix the problem?

**Comment by retronym** [comment]
@channingwalton could you cat `.idea/libraries/SBT__scala_2_10_3.xml` after running `gen-idea` and post that here?

Are you using raw SBT or Activator? (The latter apparently forces use of a particular version of sbt-idea.)

**Comment by retronym** [comment]
```
% tail build.sbt project/build.properties project/plugins.sbt
==> build.sbt <==
scalaVersion := "2.10.3"

==> project/build.properties <==
sbt.version=0.13.0

==> project/plugins.sbt <==
resolvers += "Sonatype snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.6.0-SNAPSHOT")

% sbt gen-idea > /dev/null

% tail .idea/libraries/*
==> .idea/libraries/SBT__org_scala_lang_scala_library_2_10_3.xml <==
      <root url="jar://$USER_HOME$/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.10.3.jar!/"/>
    </CLASSES>
    <JAVADOC>
      <root url="jar://$USER_HOME$/.ivy2/cache/org.scala-lang/scala-library/docs/scala-library-2.10.3-javadoc.jar!/"/>
    </JAVADOC>
    <SOURCES>
      <root url="jar://$USER_HOME$/.ivy2/cache/org.scala-lang/scala-library/srcs/scala-library-2.10.3-sources.jar!/"/>
    </SOURCES>
  </library>
</component>
==> .idea/libraries/SBT__scala_2_10_2.xml <==
  <library name="SBT: scala:2.10.2">
    <CLASSES>
      <root url="jar://$USER_HOME$/.sbt/boot/scala-2.10.2/lib/scala-library.jar!/"/>
      <root url="jar://$USER_HOME$/.sbt/boot/scala-2.10.2/lib/scala-compiler.jar!/"/>
      <root url="jar://$USER_HOME$/.sbt/boot/scala-2.10.2/lib/scala-reflect.jar!/"/>
    </CLASSES>
    <JAVADOC> </JAVADOC>
    <SOURCES> </SOURCES>
  </library>
</component>
==> .idea/libraries/SBT__scala_2_10_3.xml <==
  <library name="SBT: scala:2.10.3">
    <CLASSES>
      <root url="jar://$USER_HOME$/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.10.3.jar!/"/>
      <root url="jar://$USER_HOME$/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.10.3.jar!/"/>
      <root url="jar://$USER_HOME$/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.10.3.jar!/"/>
    </CLASSES>
    <JAVADOC> </JAVADOC>
    <SOURCES> </SOURCES>
  </library>
```

image

I do see a separate problem, however. Even though the meta-project for the SBT build doesn't have the Scala Facet attached, IntelliJs compiler still tries to compile `./project/build.scala`.

This also fails with `sbt "gen-idea no-sbt-build-module"`.

The reason is in my test I had a `.scala` file in the root of the project. This is allowed by SBT in addition to `src/main/scala`. But when using this mode, `sbt-idea` adds `.` as a source path, which picks up `./**/*.scala`. (IntelliJ can't add a directory non-recursively the source path).

We should really exclude `project` in that case.

**Comment by mpeltonen** [comment]
@retronym: release "planning" has been pretty much ad-hoc and now there seems to be a real need, so I'll try to do it by the end of the week (i.e. weekend most likely).

**Comment by retronym** [comment]
Great, thanks a lot.

**Comment by channingwalton** [comment]
OK I see my problem. When I upgraded scala in my project, and ran sbt gen-idea, the old lib was left in .idea/libraries.

I guess I should delete .idea\* before running gen-idea.

Perhaps gen-idea should do that anyway?

**Comment by jozic** [comment]
@channingwalton i think it shouldn't delete any files b/c you may have some custom settings there

**Comment by channingwalton** [comment]
is it possible to make sure that only sbt libs and scala version you depend on are included, otherwise you end up with a mix.

**Comment by retronym** [comment]
The plugin will only add references to the current set of libraries, so old ones shouldn't be more than an annoyance. Do you observe otherwise?

**Comment by channingwalton** [comment]
yes, if I update a version of a lib, I end up with both versions in the project, so what I tend to do is rm -rf .idea\* before using gen-idea

**Comment by retronym** [comment]
Can you clarify what you mean as "in the project"? In the list of libraries under "project settings", or also in the classpath of a module (under "project settings" -> "module" -> "my module" -> "dependencies").

My understanding is that it should only be the former, which is a bit annoying, but shouldn't be visible on the IntelliJ's classpath.

**Comment by retronym** [comment]
Deleting ".idea/libraries" is a more directed way to clean these up, BTW.

**Comment by channingwalton** [comment]
Yes you're right. I have got muddled as usual. Its all good.

**Comment by jozic** [comment]
i like the idea deleting libraries only, but still there should be a flag or property b/c not everyone will be happy with deleting libs by default

**Comment by retronym** [comment]
Deleting `.idea/libraries/SBT__*.xml` would be pretty safe.

**Pull request closed without merging**
