### PR TITLE
ignore generated xml and iml files from vcs by default

### PR DESCRIPTION
**Pull request by jozic**
Hi Mikko, 
here is another patch, which marks all generated files as ignored from vcs. It's enabled by default, but can be disabled using "no-ignore-generated" argument.
(I'm not sure about the name of the argument, probably it would be better to have "dont-ignore-generated")

I would be glad to hear your code review comments (and fix them, if any)
Thanks,
Eugene

### CODE REVIEW

**Comment by OlegYch** [comment]
I don't think this should be enabled by default (or added at all) for two reasons:
1. i prefer to version control some of idea configs
2. ignoring files in idea does not ignore them in command line tools, which is confusing, and imo better handled at vcs level

**Comment by jozic** [comment]
Hi Oleg, thanks for your input.
Let me add my thoughts here
1. Is totally subjective b/c I don't like to commit any of my IDE specific files (if project is shared and someone uses eclipse or whatever I don't want other people to get files they don't need)
2. That's a good one, I thought about it, but decided to go with idea ignoring as it works for me ( but it obviously  can be confusing for another person). So here is the deal, I can add an option to ignore the files using vcs instead of idea, so you can shoose which one to use . And I'm okay to make it disabled by default.

**Comment by OlegYch** [comment]
Fine by me. 
As a general note, I think that using a setting instead of argument might be better.

**Comment by mpeltonen** [comment]
I think I agree with Oleg with this one. Adding .idea and .idea_modules into .[git|hg|svn]ignore is a superior solution for the problem, or does this solution give you some added benefits?

**Comment by jozic** [comment]
Hi all, as I've said before, I agree with you guys, and I'm already working on the solution to ignore files by vcs (for now  git and svn will be supported - git is an easy one, but svn is a little bit trickier) 
The benefit of ignoring through IDEA can be that if you use some vcs, which is not supported by the plugin (e.g. cvs), you still can ignore the files (I imagine you don't see it as a benefit, it's fine, just wanted to say it works for me, so I guess it could work for someone else :) )

**Comment by mpeltonen** [comment]
But what you need to do for that support? I mean, if I add something to .gitignore, IntelliJ automatically ignores those i.e. removes matching stuff from my Changes -view. Or is there something else to it (svn doesn't work that way?)?

**Comment by jozic** [comment]
Yep, for git it's as simple as appending to .gitignore, with svn it's different, you have to use svn properties,
see http://svnbook.red-bean.com/en/1.1/ch07s02.html for more details (search for svn:ignore ).
But I'm almost there.

**Comment by mpeltonen** [comment]
Ah, of course. Luckily it's been so long since I've used svn and ignores last time :)

Also, ignores are per-directory in svn, so you'd have to recurse the whole repository if you're planning to mirror those to idea metafiles?

**Comment by OlegYch** [comment]
Please make sure this feature does not screw up existing ignores.

**Comment by jozic** [comment]
@OlegYch, sure

**Comment by mpeltonen** [comment]
Hmm, I just tried ignores with svn project, and adding a file/directory to svn:ignore automatically removes it also from my 'Changes' list in Idea. What am I missing here?

**Comment by jozic** [comment]
@mpeltonen Sorry, I haven't got your question, but to my knowledge if you ignore a file in vcs (e.g. svn) idea will ignore it too, b/c it respects vcs ignore.
Please take a look at my code changes.
I've added scripted tests for ignoring using git and svn (as well as ignoring by idea). To run the one with svn you need svn installed.
As always I'm open for your feedback

**Comment by mpeltonen** [comment]
Ah, so you were going to teach sbt-idea to execute those vcs command for ignoring, I see...

But I'm still not quite convinced that this feature is essential to sbt-idea because:
- you can very easily do the ignoring on command line by hand by means of the vcs in question
- it's a one-time operation
- you get more granularity in what you want to ignore (not everyone wants to ignore everything under .idea*, and everything under .idea is not generated by sbt-idea)

**Comment by jozic** [comment]
I agree, it's absolutely non-essential to the plugin.
This is how I use the plugin, so I thought it would be nice to have one step less. 
And it was just fun for me to implement this :)
So never mind, feel free to close it.

**Comment by fommil** [comment]
+1 for this functionality if it meets #259 which is not just for VCS, but for all the internal IntelliJ directories AND the sbt `project/target` directories.

**Pull request closed without merging**
