### PR TITLE
Project structure

### PR DESCRIPTION
**Pull request by retronym**
Tweaks to the IntelliJ module structure to more faithfully reflect the SBT build.
1. Use the project id, rather than name, as the IDEA project name. (By default, they are the same.) This necessarily matches the project reference used in the inter module dependencies.
2. Add the module base directory as a source directory if it contains .scala files, as is done by the default SBT build.

With these changes, gen-idea does a better job at importing the build of SBT itself.

### CODE REVIEW

**Comment by ijuma** [comment]
Nice!

"With these changes, gen-idea does a better job at importing the build of SBT itself."

Are there still other issues?

**Comment by retronym** [comment]
`/Users/jason/code/xsbt/main/Project.scala:63` accessed `sbt.load.BuildStructure` without qualification or import.

I expect that is related to this comment on the project  `sbtSub`: "with the sole purpose of providing certain identifiers without qualification (with a package object)" here:  https://github.com/harrah/xsbt/blob/0.10/project/Sbt.scala#L113. But haven't look at it closely.

**Comment by ijuma** [comment]
I see. Thanks.

**Comment by retronym** [comment]
Added unmanaged libs, ref #61

**Comment by ijuma** [comment]
Somewhat related to the last commit by retronym, I filed https://github.com/mpeltonen/sbt-idea/issues/67

**Pull request merged**
