### PR TITLE
delete existing xml files for libraries unless dont-delete-existing-libs argument is specified

### PR DESCRIPTION
**Pull request by jozic**
sbt-idea should delete previously created xml files for libraries (matching `SBT__*.xml` pattern)
This can be very useful after upgrading some of the libraries.

This changes default behavior as it sounds reasonable for majority of use cases. New command argument `dont-delete-existing-libs` is added to enable the _old_ mode (i.e. add, but not delete)

thanks to @retronym for the idea (https://github.com/mpeltonen/sbt-idea/pull/253#issuecomment-26059033)

### CODE REVIEW

**Comment by mpeltonen** [comment]
Merged, thanks!

**Comment by jozic** [comment]
@mpeltonen could you please cherry pick this commit to 0.12 branch and issue new snapshot release for 0.12?

**Comment by mpeltonen** [comment]
Oh, I thought I already did it the other day, but apparently forgot. Done now, thanks for notice!

**Comment by jozic** [comment]
thank you!

**Pull request merged**
