### PR TITLE
Set Default Line Encoding to UNIX

### PR DESCRIPTION
**Pull request by AlainODea**
- Generate projectCodeStyle.xml with line separator set to \n

### CODE REVIEW

**Comment by AlainODea** [comment]
I saw the coincidental notification of the close of an old Issue I created and that they were one in the same.  Sorry for the mixup :S

Hopefully this feature is still interesting enough to merge.

**Comment by mpeltonen** [comment]
Yes, I think this is useful if it helps interoperability with Windows. Merged.

**Comment by AlainODea** [comment]
Awesome.  Thank you Mikko :)

**Comment by mpeltonen** [comment]
Hmm, there is one problem though; this will currently destroy per-project code style settings that people may have already set. I think it is better to generate this file only if it does not already exist.

**Comment by mpeltonen** [comment]
I changed encodings.xml and projectCodeStyle.xml files to be generated only if they do not exist, so that we do not overwrite existing settings, which is probably not a nice thing to do.

**Comment by AlainODea** [comment]
Good call.  I wasn't sure how to do that.  This fits into the theme with
edit vs overwrite IML files as well.  I treat SBT as the master record, but
defaults like this really only apply to fresh project creation unless there
is a config for the plugin that lets users control it.

On Sunday, 25 September 2011, Mikko Peltonen <
reply@reply.github.com>
wrote:

**Pull request merged**
