### PR TITLE
Add support for com.hanhuy.sbt % android-sdk-plugin

### PR DESCRIPTION
**Pull request by pfn**
make androidSupport Option[AndroidSupport], from applying AndroidSupport
turn AndroidSupport into a trait and factor out common code
add case classes SbtAndroid and AndroidSdkPlugin

### CODE REVIEW

**Comment by SandroGrzicic** [comment]
+1

**Comment by hyysguyang** [comment]
+1

**Comment by mpeltonen** [comment]
Looks good at quick glance, thanks! I'm on a vacation currently so it may take a while to take a closer look and merge, though.

**Comment by pfn** [comment]
platformVersion isn't populated correctly when using google apis, change the api used to fix this.

**Comment by pfn** [comment]
There's an issue with my support, though, with multi-project builds (of multiple android library projects) the classes.jar gets added as a library in IDEA and I can't think of a good way of preventing this from happening.

It doesn't seem to cause any issues, but it's an ugly wart that I would prefer gone since IDEA says there's an error if you go into project structure config.

**Comment by pfn** [comment]
Can this pull request go in, and a new version published soon? I'd like to publish some of my apps that have sbt-idea as part of their plugin definitions, and I don't want to push anything that uses a local SNAPSHOT. Too much of a pain to tell people how to use.

**Comment by pfn** [comment]
for now, published to scala-sbt.org as "com.hanhuy.sbt" % "sbt-idea" % "1.5.0"

**Comment by mpeltonen** [comment]
Merged, thanks!

**Pull request closed without merging**
