### PR TITLE
Sbt 0.13

### PR DESCRIPTION
**Pull request by chwthewke**
This is the pull request for #251.

The first commit is the proposed fix for the issue.

The second one is just a bump of the plugin version in the scripted tests so that they can be run meaningfully.

### CODE REVIEW

**Comment by dispalt** [comment]
This definitely fixed a problem I was having with managed src directories appearing incorrectly when generated. +1

EDIT: sorry I meant managed

**Comment by mpeltonen** [comment]
Your commit reverts a change that was done some time ago, see #209. I.e. sbt's documentation says that plugin should generate its generated sources into plugin specific subdirectory of src_managed (see http://www.scala-sbt.org/release/docs/Howto/generatefiles.html) and not directly into it. 

Problem is that some plugins do this, some don't, and because you can't have nested source dirs in Idea, 'fixing' this like you did will break managed source dirs for some other plugins in Idea :(

Having a plugin specific subdir for generated sources makes more sense to me, as it is easier to manage incremental changes to generated sources without conflicting with other plugin's generated sources.

**Comment by chwthewke** [comment]
Hi,

I stumbled on #209 while searching for something completely unrelated a couple of days ago, and then I went and read the sbt documentation you mention. I thought a bit about it and came to the conclusion that maybe #209 is correct, except that it should really look into the subdirectories of `compile:sourceManaged` and `test:sourceManaged` instead of the subdirectories of all `managedSourceDirectories`, as the latter seems to unjustly punish plugins that declare their generated dir by appending it to `managedSourceDirectories` (which seems to be a correct, if optional, behaviour). I'll be testing this and I'll submit another pull request if this bears fruit.

**Comment by chwthewke** [comment]
Well, there's just this one troubling thing with the previous theory, which is "Why, then, is `compile:sourceManaged` initially in `managedSourceDirectories`?" That seems at odd with the text at http://www.scala-sbt.org/release/docs/Howto/generatefiles.html. Maybe this ought to be taken to sbt core for clarification, and if e.g. sbt-protobuf is at fault for appending their generated root to `compile:managedSourceDirectories`, a pull request can be submitted there.

**Pull request closed without merging**
