### PR TITLE
set fsc library

### PR DESCRIPTION
**Pull request by jozic**
Hi There, 
I've found that "gen-idea" command sets fsc to true by default but doesn't set compiler library for fsc. So after you generate IDEA files, open new project in IDEA and try to compile you get an error message "Please, set up compiler library  for project FSC". After you setup compiler library IDEA saves that info in scala_compiler.xml.
So my change generates this additional scala_compiler.xml file.
Please review.
Thanks

### CODE REVIEW

**Comment by mslinn** [comment]
+1

**Comment by analytically** [comment]
+1

**Comment by mpeltonen** [comment]
Merged, thanks!

**Comment by mslinn** [comment]
Works! Hooray!

**Comment by epishkin** [comment]
Be careful! The patch contains "scala-2.9.1" hardcoded. I guess it should get scala version from sbt.

**Comment by mslinn** [comment]
Yikes! This needs to be fixed!

**Comment by jozic** [comment]
It uses scala version setup in sbt, 2.9.1 is hardcoded in expected xml for the test project where 2.9.1 is setup. So no worries, it will pick up correct scala version.

**Comment by epishkin** [comment]
sorry, my bad

**Pull request closed without merging**
