### PR TITLE
Add ideaPackagePrefix option

### PR DESCRIPTION
**Pull request by mdekstrand**
IntelliJ supports a 'packagePrefix' attribute on source directory entries in module XML files, which then allows it to recognize classes in source files using flatter directory structures (e.g. the whole project is under `net.elehack.wendoc`, so `src/main/scala` has directories `markdown`, `dom` instead of `net/elehack/wendoc/...`).

This change adds support for configuring this package prefix on a per-project level, using an `ideaPackagePrefix` configuration option. It is a separate option defaulting to `None`, rather than using or defaulting to `ideaBasePackage`, so that it doesn't surreptitiously break peoples' projects.

### CODE REVIEW

**Comment by ijuma** [comment]
Great, most welcome.

**Comment by mpeltonen** [comment]
Merged, thanks!

**Comment by kajmagnus79** [comment]
It broke my project actually. I had to add this line to all `build.sbt` files to my three _sub_ projects, but not to my main project (from which I run `idea`):

```
ideaPackagePrefix := None
```

And now everything works again. Here is a related email thread:  https://groups.google.com/forum/?fromgroups=#!topic/simple-build-tool/bkF1IDZj4L0

(Do you know if there's any better way? Than modifying subproject build.sbt files)

Here is the output from before I "fixed" the issue:

```
[app-play] $ idea
[info] Trying to create an Idea module app-play
[info] Trying to create an Idea module dao-pgsql
[error] missing package prefix
[error] java.lang.IllegalArgumentException
[error] Use 'last' for the full log.
```

**Comment by mdekstrand** [comment]
@kajmagnus79 I haven't done anything with subprojects, so no, I don't know any better way.

I do usually put my idea configs in a `local.sbt` file, that is not checked in to version control. Slightly better than modifying your `build.sbt`.

**Comment by josh-padnick** [comment]
I'm not sure if this is an issue specific to SBT subprojects, but I am finding that including the following line in my `build.sbt` file:

``` scala
ideaPackagePrefix := Some("myModule")
```

and then running `sbt idea` will successfully add the package prefix...but then IntelliJ proceeds to "refreshing 'myProject' SBT project", and as its very last act deletes the package prefix.  Any idea why this might be happening?

Unfortunately, it has made this otherwise wonderful feature unusable.

**Pull request closed without merging**
