### PR TITLE
IDEA source dirs for generated sources (#251)

### PR DESCRIPTION
**Pull request by chwthewke**
Instead of subdirs of all `managedSourceDirectories`, use subdirs of `sourceManaged` as well as `managedSourceDirectories` themselves

As I said in conclusion of the discussion at #252, I'd like to submit a different fix for #251.

This time around, source roots include:
- the subdirectories of `sourceManaged` (in the considered config), which I think is more in line with the sbt doc at http://www.scala-sbt.org/release/docs/Howto/generatefiles.html than adding all the subdirs of all `managedSourceDirectories`, event though the latter setting is initially a list containing only `sourceManaged`.
- as well as the directories in the `managedSourceDirectories` list. Even though the doc for that setting could be seen as ambiguous ("Managed source directories, which contain sources generated by the build."), I still think it reasonable to expect that a directory added to `managedSourceDirectories` (either by a plugin or directly in a build) be a compile root. Going through a handful of codegen plugins, I saw only one (sbt-protobuf) that adds anything to `managedSourceDirectories`, and it is indeed a compile root that is added.

I've tested this fix with the project that originally prompted me to raise the issue (which uses sbt-protobuf and sbt-buildinfo), as well as with the sample project given with issue #209, and I find it to be working as expected in both cases.

### CODE REVIEW

**Comment by mpeltonen** [comment]
Does it work also if you have for example sbt-protobuf and sbt-xjc plugins in the same project? I.e. it does not add nested source directories in that case?

**Comment by chwthewke** [comment]
I'm thinking it would work, testing this right now...

**Comment by chwthewke** [comment]
Looking good except for a slight wrinkle, which is that `sourceManaged` (a.k.a `target/scala-2.10/src-managed/main` is among the source roots. This should never be a problem for plugins that properly generate their code in a subdir, since these are always included as source roots. I could explicitly remove `sourceManaged` from the list of source roots for cleanliness, but I think it might be actually better this way in case a plugin (mistakenly, as per the sbt doc) generates source files directly in `sourceManaged`. Your call, I guess.

I've pushed this test project which is a modification of the test project for #209 to https://github.com/chwthewke/sbt-idea-generated-sources.

gen-idea

**Comment by chwthewke** [comment]
I realize I should have been more explicit, but of course this tiny issue does not prevent the project from compiling in IntelliJ.

**Comment by mpeltonen** [comment]
Ok, thanks for the fix and testing! If it does not prevent the project from compiling, I guess it's ok to have the main dir also included.

**Comment by dispalt** [comment]
Thanks this definitely solves a problem for me.

**Comment by jroper** [comment]
Is this PR going to be merged anytime soon?

**Comment by mpeltonen** [comment]
This is now in 1.6.0-SNAPSHOT. Thanks @chwthewke!

**Comment by jroper** [comment]
I actually think this PR is wrong.  It should be just `managedSourceDirectories` (not sub directories of it) that get included as source directories.  Why?  Because in spite of the fact that SBT tells people to put managed sources in sub directories of the `src-managed` directory, SBT considers the root directory of any source files in there to be `src-managed`.  When compiling Scala sources, this is irrelevant, since package structures don't need to match directory structures.  But when compiling Java sources, the root directory is 100% relevant, since if the directory structure from the root directory doesn't match the package structure, you get a compile error.

This causes an issue in Play, which does generate Java code, and has to use a package structure relative to `src-managed` otherwise it won't compile.  But since sbt-idea is saying that the sub directories of `src-managed` are the source directories, these generated sources don't compile from IDEA's point of view.

See https://github.com/playframework/playframework/issues/2941.

**Comment by dispalt** [comment]
I'd like to get to the bottom of this too, since generated projects do this all differently.  Did you file an SBT ticket?

**Pull request closed without merging**
