### PR TITLE
Updated  to work with android-sdk-plugin 0.9.x

### PR DESCRIPTION
**Pull request by pfn**
android.Keys.platform turned into a TaskKey; and sbt-idea needs to be updated accordingly :-/

### CODE REVIEW

**Comment by pfn** [comment]
FYI, android-sdk-plugin is available on sbt-0.13 as well

**Comment by mpeltonen** [comment]
Cherry-picked (finally) this to sbt-0.12 branch. 

Hoping to get 0.13 branch to support this soon.

**Comment by pfn** [comment]
As an FYI, android-sdk-plugin runs on 0.13 as well, but the other one does
not

##

**Comment by mpeltonen** [comment]
Added android-sdk-plugin support to 0.13 -branch (and published new 1.6.0-SNAPSHOT). 

No support for sbt-android at this time, as I didn't find a published version of it against sbt 0.13.

**Pull request closed without merging**
