### PR TITLE
Fix for issue #93: Duplicate orderEntry elements with sbt 0.11.0

### PR DESCRIPTION
**Pull request by ijuma**
The pull request also includes a couple of unrelated (minor) improvements.

### CODE REVIEW

**Comment by ijuma** [comment]
It would be nice if you pushed a new snapshot after merging this.

**Comment by mpeltonen** [comment]
Great thanks! I'll push a snapshot later today.

**Comment by mpeltonen** [comment]
Pushed.

**Comment by ijuma** [comment]
Thanks!

**Pull request merged**
