### PR TITLE
Support for multiple source roots defined in sbt

### PR DESCRIPTION
**Pull request by teigen**
Hi, I removed the previous hard coding of paths (like src/main/scala, src/main/java etc) and is now using whatever is configured in sbt instead.
I  also fixed some tests that were broken so everything runs as it should.

Please verify that I haven't broken anything else as its been a while since I hacked on this project ;-)

/j

### CODE REVIEW

**Comment by mpeltonen** [comment]
Hi! I wondered why you had to modify the expectations for single-module-with-defaults and single-module-with-properties, because your change should not affect to them, and for me the tests only work with your master if I revert them to what they were before! Have you in any chance for example deleted the 'resources' directories locally, if the tests pass for you?

I also had to create the src/\* directory structure for multiple-source-roots test for tests to pass. Did you forgot to commit them (git doesn't add empty directories) or do we have some other difference in our setup?

**Comment by mpeltonen** [comment]
Lol, I haven't ever committed those source directories... :) Exactly the same thing with git being silent about them...

**Comment by mpeltonen** [comment]
I added the missing resources dirs to master.

**Comment by teigen** [comment]
ok, expectation-files reverted and all tests green :-)

**Comment by mpeltonen** [comment]
Merged, thanks!

**Pull request merged**
