### PR TITLE
Added FSC integration

### PR DESCRIPTION
**Pull request by benjaminparker**
I have added a default fsc option which can be overridden by specifying no-fsc

### CODE REVIEW

**Comment by mpeltonen** [comment]
Thanks, looks good!

I'm just wondering if better default would be current behavior, and command line flag would be use-fsc? For example what happens if the useFsc is generated and you have older scala plugin in idea?

**Comment by benjaminparker** [comment]
Good point. I would say
1. If the older plugin ignores this setting then we have no problem
2.  Most people will be using the latest plugin as the ide is evolving all the time so everyone wants latest version

I think 90% of people will want fsc on as default.  I'd suggest releasing with current setup with note saying tested with fsc integrated version of scala plugin

**Comment by mpeltonen** [comment]
Yep, I'm thinking along the same lines. The fsc feature makes compiling so much faster that I can't imagine why you wouldn't want to use it if you compile with idea, and supporting older versions of scala-plugin is imo not that important. If you for some reason can't update, you can use later version of sbt-idea.

**Comment by benjaminparker** [comment]
So - are you going to push this change?  I am newish to git so can I now delete my fork ?

**Comment by mpeltonen** [comment]
Could you make a pull request without version changes in Build.scala and plugins.sbt?

**Comment by benjaminparker** [comment]
Done

**Comment by mpeltonen** [comment]
Merged, thanks!

It would have been better if you modified the original commit instead of creating a new one (so that pull request didn't know anything about the version change bits), but that involves a bit more advanced git stuff.

**Comment by benjaminparker** [comment]
ok - still new to Git - will look at that on help for future

**Pull request merged**
